name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - production
    environment:
      name: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker compose -f docker-compose.yml build
      - run: docker compose -f docker-compose.yml up -d